apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-c2uy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0073-tenant/cin4s-839-0073-app/devfile-sample-c2uy@sha256:5e3828195246e50fa01b0a817338c0c56a5f3da158a34fd4fc764d0e471bf5ce
        name: my-nodejs
        resources: {}
status: {}
